[build-system]
requires = ['setuptools', 'wheel']
build-backend = 'setuptools.build_meta'

[project]
name = 'authenv-service'
version = '1.0.1'
description = 'Generic Global Authentication and Environment Properties Service'
authors = [{name = "Bibek Aryal"}]
readme = 'README.md'
requires-python = ">=3.9"
classifiers = [
    "License :: Personal Use Only",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
]
dependencies = [
    'bcrypt>=4.0.1',
    'fastapi>=0.100.0',
    'pydantic>=2.0.2',
    'pydantic_settings>=2.0.1',
    'pyjwt>=2.7.0',
    'pymongo>=4.4.0',
    'requests>=2.31.0',
    'uvicorn>=0.22.0',
]

# [project.optional-dependencies]
# pip install '.[test]'.

[project.urls]
Source = "https://github.com/bibekaryal86/authenv-service"

# [project.scripts]
